#!/bin/sh

BACKUP=$1
ARCHIVE=$2

TRASH=$BACKUP/trash/

if [ -z $BACKUP ]
then
 echo Need to supply a backup directory to archive.
 exit 1
fi
if [ ! -d $BACKUP ]
then
 echo $BACKUP does not exist.
 exit 1
fi

if [ -z $ARCHIVE ]
then
 echo Need to supply a archive directory.
 exit 1
fi
if [ ! -d $ARCHIVE ]
then
 echo $ARCHIVE does not exist.
 exit 1
fi

mkdir -p $TRASH

CURDAY=`date "+%d"`

# This is going to be cutting into the previous month
#  and perhaps the previous year.
if [ $CURDAY -le 7 ]
then
 CUTOFFMONTH=`date "+%m"`
 if [ $CUTOFFMONTH -eq 1 ]
 then
  CUTOFFMONTH=12
 else
  CUTOFFMONTH=$(($CUTOFFMONTH - 1))
 fi
 
 CUTOFFYEAR=`date "+%Y"`
 if [ $CUTOFFMONTH -eq 1 ]
 then
  CUTOFFYEAR=$(($CUTOFFYEAR - 1))
 fi

 # See if date 28 - (7 - CURDAY) exists. then increase 28 up to 31.
 for (( CHECKDATE=$((28 - (7 - $CURDAY)));
        $CHECKDATE <= 31;
        CHECKDATE=$(($CHECKDATE + 1)) ))
 do
  CHECKDATES="$CHECKDATES $CHECKDATE"
 done

 for LASTDAY in $CHECKDATES
 do
  if [ -z $CUTOFFDAY ]
  then
   if test -e $BACKUP/backup-cvs-$CUTOFFYEAR-$CUTOFFMONTH-$LASTDAY.dmg
   then
    CUTOFFDAY=$LASTDAY
   fi
  fi
 done
else
 CUTOFFDAY=$(($CURDAY - 7))
 CUTOFFMONTH=`date "+%m"`
 CUTOFFYEAR=`date "+%Y"`
fi

# Find the oldest file matching the cutoff date
cd $BACKUP

while [ ! -e backup-cvs-$CUTOFFYEAR-$CUTOFFMONTH-$CUTOFFDAY.dmg ]
do
 if [ $CUTOFFDAY -eq 1 ]
 then
  if [ $CUTOFFMONTH -eq 1 ]
  then
   CUTOFFDAY=31
   CUTOFFMONTH=12
   CUTOFFYEAR=$(($CUTOFFYEAR - 1))
  else
   CUTOFFDAY=31
   CUTOFFMONTH=$(($CUTOFFMONTH - 1))
  fi
 else
  CUTOFFDAY=$(($CUTOFFDAY - 1))
 fi

 if [ $CUTOFFYEAR -eq $((`date "+%Y"`- 2)) ]
 then
  echo Nothing to archive.
  exit 1
 fi
done

CUTOFFDATE=$CUTOFFYEAR-$CUTOFFMONTH-$CUTOFFDAY

OLDESTCUTOFF=`ls -1t backup-*-$CUTOFFDATE.dmg | tail -1`

# Find the files older than the cutoff date and clean them up
FILESTOCLEANUP=`find $BACKUP -not -newer $OLDESTCUTOFF -and -not -name $OLDESTCUTOFF`

echo These files would be trashed: $FILESTOCLEANUP
mv $FILESTOCLEANUP $TRASH
#rm $FILESTOCLEANUP

# Copy the cutoff date files to the archive location
cp $BACKUP/backup-*-$CUTOFFDATE.dmg $ARCHIVE

echo These files should be archived:
echo `ls -1t $ARCHIVE`
