#!/bin/sh

# bug. picked 2/16, 2/28, 3/2. It missed 2/23 (2005)

BACKUP=$1
ARCHIVE=$2

if [ -z $BACKUP ]
then
 echo Need to supply a backup directory to archive.
 exit 1
fi
if [ ! -d $BACKUP ]
then
 echo $BACKUP does not exist.
 exit 1
fi

if [ -z $ARCHIVE ]
then
 echo Need to supply a archive directory.
 exit 1
fi
if [ ! -d $ARCHIVE ]
then
 echo $ARCHIVE does not exist.
 exit 1
fi

CURDAY=`date "+%e"`

# This is going to be cutting into the previous month
#  and perhaps the previous year.
if [ $CURDAY -le 7 ]
then
 CUTOFFYEAR=`date "+%Y"`
 CUTOFFMONTH=`date "+%m"`
 LASTDAY=31
 if [ $CUTOFFMONTH -eq 1 ]
 then
  CUTOFFMONTH=12
  CUTOFFYEAR=$(($CUTOFFYEAR - 1))
 else
  CUTOFFMONTH=$(($CUTOFFMONTH - 1))
 fi

 # Handle less than 31 days months
 if [ $CUTOFFMONTH -eq 2 ]
 then
  LASTDAY=28
 else
  if [ $CUTOFFMONTH -eq 4 -o $CUTOFFMONTH -eq 6 -o $CUTOFFMONTH -eq 9 -o $CUTOFFMONTH -eq 11 ]
  then
   LASTDAY=30
  fi
 fi

 if [ $CUTOFFMONTH -le 9 ]
 then
  CUTMONTH="0$CUTOFFMONTH"
  CUTOFFMONTH=$CUTMONTH
 fi

 # See if date LASTDAY - (7 - CURDAY) exists. then increase up to LASTDAY.
 for (( CHECKDATE=$(($LASTDAY - (7 - $CURDAY)));
        $CHECKDATE <= $LASTDAY;
        CHECKDATE=$(($CHECKDATE + 1)) ))
 do
  CHECKDATES="$CHECKDATES $CHECKDATE"
 done

 for LASTDAY in $CHECKDATES
 do
  if [ -z $CUTOFFDAY ]
  then
   if test -e $BACKUP/backup-$CUTOFFYEAR-$CUTOFFMONTH-$LASTDAY.dmg
   then
    CUTOFFDAY=$LASTDAY
   fi
  fi
 done
else
 CUT=$(($CURDAY - 7))
 if [ $CUT -le 9 ]
 then
  CUTOFFDAY="0$CUT"
 else
  CUTOFFDAY=$CUT
 fi
 CUTOFFMONTH=`date "+%m"`
 CUTOFFYEAR=`date "+%Y"`
fi

# Find the oldest file matching the cutoff date
cd $BACKUP

echo Archive cut-off date: $CUTOFFYEAR-$CUTOFFMONTH-$CUTOFFDAY

while [ ! -e backup-$CUTOFFYEAR-$CUTOFFMONTH-$CUTOFFDAY.dmg ]
do
 if [ $CUTOFFDAY -eq 1 ]
 then
  if [ $CUTOFFMONTH -eq 1 ]
  then
   CUTOFFDAY=31
   CUTOFFMONTH=12
   CUTOFFYEAR=$(($CUTOFFYEAR - 1))
  else
   CUTOFFDAY=31
   CUTOFFMONTH=$(($CUTOFFMONTH - 1))
  fi
 else
  CUTOFFDAY=$(($CUTOFFDAY - 1))
 fi

 if [ $CUTOFFYEAR -eq $((`date "+%Y"`- 2)) ]
 then
  echo Nothing to archive.
  exit 1
 fi
done

CUTOFFDATE=$CUTOFFYEAR-$CUTOFFMONTH-$CUTOFFDAY

# Find the files older than the cutoff date and clean them up
FILESTOCLEANUP=`find $BACKUP -not -newer backup-$CUTOFFDATE.dmg -and -not -name backup-$CUTOFFDATE.dmg`

# Copy the cutoff date files to the archive location
# Copy it before removing the trashed ones, just in case
#  it is symlink to one of the trash items.
PRG="$0"
PROG_HOME=`dirname "$PRG"`
PROG_HOME=`cd "$PROG_HOME" && pwd`
$PROG_HOME/split $BACKUP/backup-$CUTOFFDATE.dmg
cp $BACKUP/backup-$CUTOFFDATE* $ARCHIVE

echo These files are being trashed: $FILESTOCLEANUP
rm $FILESTOCLEANUP

echo These files should be archived:
echo `ls -1t $ARCHIVE`
