#!/bin/sh

BACKUP=/tmp/backup
DEST=/tmp/backup/archive/

mkdir -p $DEST

CURDAY=`date "+%d"`

# On the 1st of the month, clean up everything prior to
#  the 15th of the previous month. Copy the data from the
#  15th of the previous month to the archive location and
#  send an email reminder.

# On the 15th of the month, clean up everything prior to
#  the 1st of the current month. Copy the data from the
#  1st of the current month to the archive location and 
#  send an email reminder.

if [ $CURDAY -eq 1 ]
then
 CUTOFFDAY=15
 CUTOFFMONTH=`date "+%m"`
 if [ $CUTOFFMONTH -eq 1 ]
 then
  CUTOFFMONTH=12
 else
  CUTOFFMONTH=$(($CUTOFFMONTH - 1))
 fi
 
 CUTOFFYEAR=`date "+%Y"`
 if [ $CUTOFFMONTH -eq 12 ]
 then
  CUTOFFYEAR=$(($CUTOFFYEAR - 1))
 fi
elif [ $CURDAY -eq 15 ]
then
 CUTOFFDAY=1
 CUTOFFMONTH=`date "+%m"`
 CUTOFFYEAR=`date "+%Y"`
else
 echo Fake Day!
 # Fake out cutoff date with a 2 day older test
 CUTOFFDAY=$(($CURDAY - 2))
 CUTOFFMONTH=`date "+%m"`
 CUTOFFYEAR=`date "+%Y"`
fi

CUTOFFDATE=$CUTOFFYEAR-$CUTOFFMONTH-$CUTOFFDAY

# Find the oldest file matching the cutoff date
cd $BACKUP
OLDESTCUTOFF=`ls -1t backup-*-$CUTOFFDATE.dmg | tail -1`

# Find the files older than the cutoff date and clean them up
FILESTOCLEANUP=`find $BACKUP -not -newer $OLDESTCUTOFF -and -not -name $OLDESTCUTOFF`

rm $FILESTOCLEANUP

# Copy the cutoff date files to the archive location
cp $BACKUP/backup-*-$CUTOFFDATE.dmg $DEST
