#!/bin/sh

FULL_ARCHIVE=$1

if [ -z $FULL_ARCHIVE ]
then
 echo Need to supply an archive.
 exit 1
fi
if [ ! -f $FULL_ARCHIVE ]
then
 echo $FULL_ARCHIVE does not exist.
 exit 1
fi

ARCHIVE_DIR=`dirname $FULL_ARCHIVE`
ORIGINAL_ARCHIVE=`basename $FULL_ARCHIVE`
ORIGINAL_NAME=`basename -s .dmg $FULL_ARCHIVE`

# Split the archive into chunks if too big
ARCHIVE_SIZE=`du -k $FULL_ARCHIVE | cut -f1`
# DVD - 4.7GB == 4.7 * 1024 * 1024 == 4812.8 * 1024 ~= 4700 * 1024 KB
CUTOFF_SIZE=$((4700 * 1024))
if [ $ARCHIVE_SIZE -ge $CUTOFF_SIZE ]
then
  NUM_SEGS=$(($ARCHIVE_SIZE / $CUTOFF_SIZE))
  if [ $(($ARCHIVE_SIZE % $CUTOFF_SIZE)) -ge 1 ]
  then
    NUM_SEGS=$(($NUM_SEGS + 1))
  fi

  cd $ARCHIVE_DIR
  ARCHIVE_SEG=$ORIGINAL_NAME-seg

  echo Splitting $ORIGINAL_ARCHIVE
  hdiutil segment -o $ARCHIVE_SEG -segmentCount $NUM_SEGS $ORIGINAL_ARCHIVE

  CUR_SEG=1
  while [ $CUR_SEG -le $NUM_SEGS ]
  do
    SEG_DIR=$ARCHIVE_SEG-$CUR_SEG
    mkdir $SEG_DIR

    if [ $CUR_SEG -eq 1 ]
    then
      mv $ARCHIVE_SEG.dmg $SEG_DIR
    else
      if [ $CUR_SEG -le 9 ]
      then
        CUR_INDEX="00$CUR_SEG"
      else
        if [ $CUR_SEG -le 99 ]
        then
          CUR_INDEX=0$CUR_SEG
        else
          CUR_INDEX=$CUR_SEG
        fi
      fi
      
      mv $ARCHIVE_SEG.$CUR_INDEX.dmgpart $SEG_DIR
    fi

    echo Creating $SEG_DIR.dmg
    hdiutil create -srcfolder $SEG_DIR $SEG_DIR.dmg

    rm -rf $SEG_DIR

    CUR_SEG=$((CUR_SEG + 1))
  done

  rm $FULL_ARCHIVE
fi
